version: '3'
services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=4000

  category:
    build: ./microservices/category
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
  
  challenge:
    build: ./microservices/challenge
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}

  item:
    build: ./microservices/item
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    
    
  user:
    build: ./microservices/user
    container_name: users
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: